string="Iam Akshaya "
print(len(string))
print(string.upper())
print(string.lower())
print(string[:2])
print(string[2:8])
print(string.islower())
print(string.isupper())
print(string.count('a'))
print(string[::])
print(string[2:-2])
print(string[::-1])
print(string.split())
